[package]
name = "gen_code"
version = "0.1.0"
edition = "2018"


[lib]
proc_macro = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quote = "1.0.7"
syn = "1.0.40"
proc-macro2 = "1.0.20"
